name: CLI Template CI

on:
  push:
    branches: ['**']
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"
  pull_request:
    branches: ['**']
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"

jobs:
  cli-template:
    runs-on: ubuntu-latest
    container:
      image: solanalabs/solana:stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify tools are available
        run: |
          solana --version
          cargo-build-sbf --help || true
          cargo build-sbf --help || true
          rustup target list | grep sbf || true

      - name: Install sf CLI
        run: cd star_frame_cli && cargo install --path .

      - name: Generate test project
        run: sf new test_project

      - name: Build generated project
        run: |
          cd test_project
          cargo build-sbf