name: CLI Template CI

on:
  push:
    branches: ['**']
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"
  pull_request:
    branches: ['**']
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"

jobs:
  cli-template:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl build-essential pkg-config libssl-dev ca-certificates git

  #     - name: Setup Rust
  #       uses: actions-rust-lang/setup-rust-toolchain@v1
  #       with:
  #         cache: 'false'
  #         toolchain: 'nightly'

      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        shell: bash

      - name: Install Solana
        run: |
          curl -sSfL https://release.solana.com/v1.18.26/install | sh.

      - name: Verify Rust and Solana CLI
        run: |
          rustup default nightly
          cargo --version
          solana --version

      - name: Install sf CLI
        run: |
          cd star_frame_cli
          RUSTFLAGS="-A warnings" cargo install --path .

      - name: Generate test project
        run: |
          cd /tmp
          sf new test_project

      # - name: Install sbpf-linker
      #   run: cargo install sbpf-linker     
  
      - name: Build SBF program
        run: |
          cd /tmp/test_project
          cargo +nightly build-sbf

      - name: Run tests
        run: |
          cd /tmp/test_project
          cargo test

    