name: cli-template

on:
  push:
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"
  pull_request:
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"


jobs:
  cli-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"

      - name: Install sf CLI
        run: cargo install --path star_frame_cli

      - name: Generate test project
        run: sf new test_project

      - name: Build generated project
        run: |
          cd test_project
          cargo build-sbf
