name: CLI Template CI

on:
  push:
    branches: ['**']
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"
  pull_request:
    branches: ['**']
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"

jobs:
  cli-template:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl build-essential pkg-config libssl-dev ca-certificates git bzip2

      - name: Setup Rust nightly 1.92
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-1.92.0
          profile: minimal
          cache: false

      - name: Remove rust-toolchain override
        run: |
          [ -f rust-toolchain.toml ] && mv rust-toolchain.toml rust-toolchain.toml.bak || true

      - name: Install Solana CLI v1.18.26
        shell: bash
        run: |
          curl -sSfL https://github.com/solana-labs/solana/releases/download/v1.18.26/solana-release-x86_64-unknown-linux-gnu.tar.bz2 -o solana.tar.bz2
          mkdir -p $HOME/.local/share/solana/install/active_release
          tar -xjf solana.tar.bz2 -C $HOME/.local/share/solana/install/active_release --strip-components=1
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Verify Rust and Solana CLI
        shell: bash
        run: |
          source $HOME/.cargo/env
          cargo +nightly --version
          rustc +nightly --version
          solana --version

      - name: Install sf CLI
        shell: bash
        run: |
          source $HOME/.cargo/env
          cd star_frame_cli
          RUSTFLAGS="-A warnings" cargo +nightly install --path .

      - name: Generate test project
        shell: bash
        run: |
          source $HOME/.cargo/env
          cd /tmp
          sf new test_project

      - name: Downgrade resolver in test project
        shell: bash
        run: |
          cd /tmp/test_project
          # Patch resolver for compatibility
          sed -i 's/^resolver\s*=\s*"3"/resolver = "2"/' Cargo.toml

      - name: Patch star_frame dependencies in registry
        shell: bash
        run: |
          cd /tmp/test_project
          cargo +nightly fetch
          find ~/.cargo/registry/src -name "Cargo.toml" -path "*/star_frame*/Cargo.toml" -exec sed -i 's/^resolver\s*=\s*"3"/resolver = "2"/' {} \;

      - name: Generate Cargo lockfile
        shell: bash
        run: |
          cd /tmp/test_project
          cargo +nightly generate-lockfile

      - name: Build SBF program
        shell: bash
        run: |
          source $HOME/.cargo/env
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          cd /tmp/test_project
          cargo +nightly build-sbf -- -Znext-lockfile-bump

      - name: Run tests
        shell: bash
        run: |
          source $HOME/.cargo/env
          cd /tmp/test_project
          cargo +nightly test
