name: CLI Template CI

on:
  push:
    branches: ['**']
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"
  pull_request:
    branches: ['**']
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"

jobs:
  cli-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Solana CLI
        uses: solana-labs/solana@v2
        with:
          solana_version: 'stable'
          tools: 'all'

      - name: Install cargo-build-sbf
        run: |
          cargo install cargo-build-bpf
          cargo install cargo-build-sbf

      - name: Build and install sf CLI
        run: |
          cd star_frame_cli
          cargo install --path .

      - name: Generate test project
        run: sf new test_project

      - name: Build generated project
        run: |
          cd test_project
          cargo build-sbf

      - name: Verify program build
        run: |
          cd test_project
          ls -la target/deploy/