name: CLI Template CI

on:
  push:
    branches: ['**']
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"
  pull_request:
    branches: ['**']
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"

jobs:
  cli-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana-install init

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-build-sbf
        run: cargo install cargo-build-sbf

      - name: Install sf CLI
        run: cargo install --path star_frame_cli

      - name: Generate test project
        run: sf new test_project

      - name: Build generated project
        run: |
          cd test_project
          cargo build-sbf
