name: CLI Template CI

on:
  push:
    branches: ['**']
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"
  pull_request:
    branches: ['**']
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"

jobs:
  cli-template:
    runs-on: ubuntu-latest
    # container:
    #   image: solanalabs/solana:edge

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl build-essential pkg-config libssl-dev ca-certificates git

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: 'false'
          toolchain: 'nightly'

      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/stable/install)"

      - name: Verify Rust and Solana CLI
        run: |
          rustup default nightly
          cargo --version
          solana --version

      - name: Install sf CLI
        run: |
          cd star_frame_cli
          RUSTFLAGS="-A warnings" cargo install --path .

      - name: Generate test project
        run: |
          cd /tmp
          sf new test_project

      - name: Set Rust edition to 2021
        run: |
          cd /tmp/test_project
          sed -i 's/^edition\s*=\s*".*"/edition = "2021"/' Cargo.toml
          
      - name: Downgrade resolver for compatibility
        run: |
          cd /tmp/test_project
          sed -i 's/^resolver\s*=\s*"3"/resolver = "2"/' Cargo.toml
          
      - name: Generate lockfile
        run: |
          cd /tmp/test_project
          cargo generate-lockfile
          
      - name: Patch star_frame dependencies to use resolver 2
        run: |
          # Download dependencies first
          cd /tmp/test_project
          cargo fetch
          # Patch all star_frame crates in the registry
          find ~/.cargo/registry/src -name "Cargo.toml" -path "*/star_frame*/Cargo.toml" -exec sed -i 's/^resolver\s*=\s*"3"/resolver = "2"/' {} \;

      - name: Build SBF program
        run: |
          cd /tmp/test_project
          cargo build-sbf

      - name: Run tests
        run: |
          cd /tmp/test_project
          cargo test