name: CLI Template CI

on:
  push:
    branches: ['**']
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"
  pull_request:
    branches: ['**']
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"

jobs:
  cli-template:
    runs-on: ubuntu-latest
    container:
      image: solanalabs/solana:edge

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl build-essential pkg-config libssl-dev ca-certificates git

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: 'false'
          toolchain: 'nightly'

      - name: Verify Rust and Solana CLI
        run: |
          rustup default nightly
          cargo --version
          solana --version

      - name: Install sf CLI
        run: |
          cd star_frame_cli
          RUSTFLAGS="-A warnings" cargo install --path .

      - name: Generate test project
        run: |
          cd /tmp
          sf new test_project

      - name: Install sbpf-linker
        run: cargo install sbpf-linker     
  
      - name: Build SBF program
        run: |
          cd /tmp/test_project
          cargo build-bpf

      - name: Run tests
        run: |
          cd /tmp/test_project
          cargo test