name: CLI Template CI

on:
  push:
    branches: ['**']
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"
  pull_request:
    branches: ['**']
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"

jobs:
  cli-template:
    runs-on: ubuntu-latest
    container:
      image: solanalabs/solana:edge

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl build-essential pkg-config libssl-dev ca-certificates git

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: 'false'
          toolchain: '1.90.0'

      - name: Verify Rust and Solana CLI
        run: |
          rustup default 1.90.0
          rustup update 1.90.0
          cargo --version
          solana --version

      - name: Install sf CLI
        run: |
          cd star_frame_cli
          cargo install --path .

      - name: Generate test project
        run: |
          cd /tmp
          sf new test_project
          find /tmp/test_project -name Cargo.lock -delete

      - name: Set Rust edition to 2021
        run: |
          cd /tmp/test_project
          sed -i 's/^edition\s*=\s*".*"/edition = "2021"/' Cargo.toml

      - name: Build SBF program
        run: |
          cd /tmp/test_project
          cargo build-sbf 

      - name: Run tests
        run: |
          cd /tmp/test_project
          cargo test