name: CLI Template CI

on:
  push:
    branches: ['**']
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"
  pull_request:
    branches: ['**']
    paths:
      - "star_frame_cli/**"
      - "star_frame_cli/src/template/**"

jobs:
  cli-template:
    runs-on: ubuntu-latest
    container:
      image: solanalabs/solana:stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup target add bpfel-unknown-unknown

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana-install init

      - name: Install sf CLI
        run: |
          cd star_frame_cli
          cargo install --path .

      - name: Generate test project
        run: sf new test_project

      - name: Build generated project
        run: |
          cd test_project
          cargo build-sbf
